// import type { Metadata } from "next";
// import localFont from "next/font/local";
// import "./globals.css";






// const greenfont = localFont({
//   src: "./fonts/Greenfont.woff2",
//   variable: "--font-greenfont",
//   weight: "100 900",
// });

// export const metadata: Metadata = {
//   manifest:"/manifest.json",  
//   title: "Animated GreenGuard",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">

//       <body
//         className={`${greenfont.variable}  antialiased`}
//       >
   
//         {children}
          
       
//       </body>
//     </html>
//   );
// }



import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const greenfont = localFont({
  src: "./fonts/Greenfont.woff2",
  variable: "--font-greenfont",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Animated GreenGuard",
  description: "Generated by create next app",
  themeColor: "#008000",
  manifest: "/manifest.json",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/* Explicitly add manifest and theme color meta for Chrome */}
        <link rel="manifest" href="/manifest.json" />
        <meta name="theme-color" content="#008000" />
      </head>
      <body className={`${greenfont.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
